### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by ulloaa** [IEDB/TCRMatch#14]
Hello, 

I am having issues compiling tcrmatch from source on CentOS 7. Do you by any chance provide the tcrmatch docker container on dockerhub and if so, could you please share the link? Alternatively, could you please provide more guidance as to what versions of gcc and cmake etc are needed for compiling? Thanks!

**Comment by acrinklaw** [comment]
Hi @ulloaa I will upload a Docker container to dockerhub while I figure out how to make the install process easier.

**Comment by acrinklaw** [comment]
I have added a Docker image to [Dockerhub](https://hub.docker.com/repository/docker/acrinklaw/tcrmatch). Please let me know if you have any issues or suggestions. Thanks

**Comment by misrak** [comment]
Hello, 

Can you also add it to conda? Thank you. 

This is what I am getting while compiling it. Can you help me with it? Maybe I have missed something here.


`[ 50%] Building CXX object CMakeFiles/tcrmatch.dir/src/tcrmatch.cpp.o
In file included from /usr/include/c++/4.8.2/array:35:0,
                 from /home/misra.kaalindi/beefe/tools/TCRMatch-master/src/tcrmatch.cpp:1:
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
/home/misra.kaalindi/beefe/tools/TCRMatch-master/src/tcrmatch.cpp:12:1: error: ‘array’ in namespace ‘std’ does not name a type
 std::array<std::array<float, 20>, 20> k1;
 ^
`

**Comment by ulloaa** [comment]
> I have added a Docker image to [Dockerhub](https://hub.docker.com/repository/docker/acrinklaw/tcrmatch). Please let me know if you have any issues or suggestions. Thanks

Thanks, I have pulled the docker image and seems to be working. Thanks again!

**Comment by acrinklaw** [comment]
> Hello,
> 
> Can you also add it to conda? Thank you.
> 
> This is what I am getting while compiling it. Can you help me with it? Maybe I have missed something here.
> 
> ```
> [ 50%] Building CXX object CMakeFiles/tcrmatch.dir/src/tcrmatch.cpp.o
> In file included from /usr/include/c++/4.8.2/array:35:0,
>                  from /home/user/tools/TCRMatch-master/src/tcrmatch.cpp:1:
>  /usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 
>  2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler 
>  options.
>   #error This file requires compiler and library support for the \
>   ^
> 
>  /home/user/tools/TCRMatch-master/src/tcrmatch.cpp:12:1: error: ‘array’ in namespace ‘std’ does not name a type
>   std::array<std::array<float, 20>, 20> k1;
>  ^
> ```

This just seems like your compiler is old and doesn't support the standard I'm using. What version of gcc does your system have?
