### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by schristley** [IEDB/TCRMatch#2]
Get a segmentation fault when comparing these two sequences, not sure why, I think they are both valid.

```
$ python3
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tcrmatch_c import tcrmatch
>>> tcrmatch('CASSTWEKETQYF', 'CASSLVVWDRGGNOPQHF')
Segmentation fault
```

**Comment by schristley** [comment]
happened for some others, CASSOTGQYAEQF, CASSQETDIVFNOPQHF

I think I see, these all have 'O' in them which is not one of the standard amino acids.

Would be more friendly to throw a python exception.

**Comment by acrinklaw** [comment]
Sorry Scott, just saw this - I'll go ahead and add some validation and make it more explicit when errors happen. Thanks for pointing this out!

**Comment by acrinklaw** [comment]
I rewrote the entire script to just C++, I now have error checking for invalid amino acids and the script is greatly optimized. I will have to open a new issue to recreate the simple "tcrmatch(seq1, seq2)" method though.
