### ISSUE TITLE
# of threads input doesn't account for negative numbers or decimals

### ISSUE THREAD

**Issue by danielmarrama** [IEDB/TCRMatch#20]
The `-t` parameter is supposed to take the number of threads to run the tool if on a machine with more than one core. Entering negative numbers and decimals as the parameter does not output an error.

**Comment by acrinklaw** [comment]
Fixed by [this commit](https://github.com/IEDB/TCRMatch/commit/96b552ff157283316149f5eb9397336a3ed05197)

**Comment by acrinklaw** [comment]
As an added bonus, if none is provided it now defaults to 1 as it should
