### ISSUE TITLE
output should be in various formats specified

### ISSUE THREAD

**Issue by danielmarrama** [IEDB/TCRMatch#21]
Output is not file specific (e.g. .csv, .xlsx), there should be multiple types of files supported for the output.

**Comment by acrinklaw** [comment]
I'm down for .csv output, which is easy to implement. I'd prefer to avoid .xlsx or other formats, .csv files can be opened fine in Excel (also Excel makes me sad)

**Comment by danielmarrama** [comment]
Agreed. Let's do .csv only for now.
