### ISSUE TITLE
similarity metric threshold cannot exceed 1, but runs anyway, also negative numbers

### ISSUE THREAD

**Issue by danielmarrama** [IEDB/TCRMatch#23]
With the `-s` parameter, a user can specify the similarity threshold, but this cannot exceed 1. It will take any number greater than 1 and it also takes negative number. This should also produce an error.

**Comment by acrinklaw** [comment]
Fixed by [this commit](https://github.com/IEDB/TCRMatch/commit/96b552ff157283316149f5eb9397336a3ed05197)
