### ISSUE TITLE
Harbor Credentials

### ISSUE THREAD

**Issue by acrinklaw** [IEDB/TCRMatch#24]
Hey @jgbaum I'd like to create a 1.0 release of TCRMatch after I address the last 2 issues Dan opened up, but I wanted to verify that the harbor credentials are in the repository settings beforehand so I know the github action will work

Hope you've been doing well :-)

**Comment by jgbaum** [comment]
Hi @acrinklaw,

Sorry I didn't see this until @danielmarrama pinged me in Gitlab.  I've added the credentials as HARBOR_USER and HARBOR_PWD as repository secrets.  Please let me know if issues arise.

Thanks,

J

**Comment by acrinklaw** [comment]
Awesome, thanks @jgbaum and no worries. Having separate Github and Gitlab can be a pain in the ass. I'll try to use email first if anything goes wrong
