### ISSUE TITLE
No headers on output

### ISSUE THREAD

**Issue by danielmarrama** [IEDB/TCRMatch#28]
From @khaeuk: "It will be better to have header for the output, so that it's clear to the users.
(I think it's suppose to be 'input sequence', 'matching sequence', and 'score')"

From me: I know this is because of the process_output.py script, but maybe the user just wants initial output so adding headers would be good? 

![image](https://user-images.githubusercontent.com/28754746/139940101-d35d8aec-5e47-44f9-be26-6b6efd953c00.png)

**Comment by acrinklaw** [comment]
This was also brought up by Scott, +1 definitely should add. Or just remove the need by unifying the 2 scripts
