### ISSUE TITLE
Add trimming of C and F/W amino acids from input CDR3 sequences by default

### ISSUE THREAD

**Issue by wchronister** [IEDB/TCRMatch#31]
The tool should, by default, remove the C...F/W residues from each input CDR3 sequence, similar to how the web server version trims by default (see "Trim sequences" checkbox at http://tools.iedb.org/tcrmatch/). An option should be added to prevent trimming of input sequences if desired by the user (e.g., "--overrideTrimming").

**Comment by acrinklaw** [comment]
needs to be prioritized, I'll try to add a fix this weekend @wchronister

**Comment by acrinklaw** [comment]
Fixed in #35
