### ISSUE TITLE
please add a version number output

### ISSUE THREAD

**Issue by schristley** [IEDB/TCRMatch#37]
In workflows, we like to output the versions of all the tools for provenance. Something simple like this:

```
./tcrmatch -v
1.0.2
````

You can get fancy and generate the version from the git tag, but tcrmatch might not change much so hard-coding the version string in the cpp file maybe easiest, just have to remember to manually change with new release.

```
#define VERSION "1.0.2"
```

**Comment by acrinklaw** [comment]
I'd be more than happy to add versioning to the tool - a bit of an oversight that it wasn't already incorporated. However in reference to #38 , that is something that would have to be addressed on the IEDB side of things. Hopefully someone who is still around in Bjoern's lab can get back to you on that.

**Comment by acrinklaw** [comment]
Added in #39. Trimming is also a part of v1.0.3. Let me know if there are any issues

**Comment by schristley** [comment]
@raphaeltrevizani Don't forget to update the version number in tcrmatch.cpp when generating a new release.
