### ISSUE TITLE
CEDAR

### ISSUE THREAD

**Issue by saramoein372** [IEDB/TCRMatch#45]
Hello,

I have a question about CEDAR_data.tsv file in the data folder.
It is supposed to be cancer antigenes, but I see many antigenes related to influenza, Human herpesvirus 5,...

How this is happening? I expect to see only cancer epitopes and antigenes.

Is there any better file to use as the database for cancer epitopes?

Thanks,
Sara

**Comment by raphaeltrevizani** [comment]
Hi Sara. Thank you for your input. We're currently coordinating with the IEDB/CEDAR team and double checking the algorithm that was used to generate the CEDAR_data.tsv file to ensure the data is correct.

**Comment by raphaeltrevizani** [comment]
I updated the file with what CEDAR provided me that includes only cancer epitopes.

**Comment by saramoein372** [comment]
Thank you so much! I try with new dataset.

Best
