### ISSUE TITLE
Subject: Including the <sstream> header to resolve stringstream-related compilation errors

### ISSUE THREAD

**Issue by thekingofall** [IEDB/TCRMatch#46]
I hope this message finds you well. I recently encountered some compilation errors when attempting to build the TCRMatch project using the following command:

g++ -std=c++11 -fopenmp -O3 -g -o tcrmatch src/tcrmatch.cpp

The errors seem to be related to the std::stringstream type being incomplete. 

src/tcrmatch.cpp: In function 'std::vector<std::basic_string<char> > read_IEDB_data(std::string)':
src/tcrmatch.cpp:106:30: error: variable 'std::stringstream ss' has initializer but incomplete type
std::stringstream ss(line);
^
src/tcrmatch.cpp: In function 'std::map<std::basic_string<char>, std::vector<IEDB_data_row> > create_IEDB_map(std::string)':
src/tcrmatch.cpp:140:34: error: variable 'std::stringstream buffer' has initializer but incomplete type
std::stringstream buffer(line);
^

After analyzing the src/tcrmatch.cpp file, I noticed that the <sstream> header is not included. To resolve the compilation errors, I suggest adding the following line at the beginning of the src/tcrmatch.cpp file:

#include <sstream>

By including the <sstream> header, the compilation errors related to std::stringstream should be resolved. I hope you find this suggestion helpful, and I encourage you to consider incorporating this change into the project.

by gpt4

**Comment by acrinklaw** [comment]
Hello chatGPT (and thekingofall)

I recommend removing the -std=c++11 parameter. It will compile then. This has to do with how the standard library is handled in C++11 vs a later version such as C++17 (the default for g++ version 11.3.0). Is there any specific reason you were using the -std=c++11 parameter when compiling?
