### ISSUE TITLE
Running TCRMatch with incomplete CDR3 sequences

### ISSUE THREAD

**Issue by seunghun23** [IEDB/TCRMatch#50]
Hi,

I am using CDR3 aa sequence from a TRB output from MixCR to run TCRMatch, and these outputs sometimes
have incompletely translated CDR3 aa sequence such as CASSPS * ETQYF with asterisk or CASSQSIA_VNNEKLFF with underscore, and TCRMatch outputs an error message such as  "Invalid amino acid found in CASSQSN*G_SSGNTIYF at position 8."
Is there a way to identify matching TCR for incomplete CDR3 sequences?

Thanks,
Seung Hun

**Comment by raphaeltrevizani** [comment]
Hi Seung Hun. No, currently there isn't.
