### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by parvathisudha** [IEDB/TCRMatch#51]
Hi, 

I am trying to install TCRMatch 1.1.1 in our HPC system. I am getting an internal compiler error.
Can you please check this error?

The loaded modules include: gcc/12.1.0, and python/3.9.8

[parkanha@i27 TCRMatch-1.1.1]$ make
g++ -std=c++11 -fopenmp -O3 -g -o tcrmatch src/main.cpp 
In file included from src/main.cpp:3:
src/tcrmatch.cpp:80:1: internal compiler error: Illegal instruction
   80 | float P_BETA = 0.11387;
      | ^~~~~
0xd96f16 crash_signal
	../.././gcc/toplev.cc:322
0xd02913 real_from_string(real_value*, char const*)
	../.././gcc/real.cc:2110
0xd032eb real_from_string3(real_value*, char const*, format_helper)
	../.././gcc/real.cc:2176
0x8d0a3d interpret_float
	../.././gcc/c-family/c-lex.cc:1035
0x8d20f8 c_lex_with_flags(tree_node**, unsigned int*, unsigned char*, int)
	../.././gcc/c-family/c-lex.cc:517
0x7afb36 cp_lexer_get_preprocessor_token
	../.././gcc/cp/parser.cc:864
0x7febcf cp_lexer_new_main
	../.././gcc/cp/parser.cc:663
0x7febcf c_parse_file()
	../.././gcc/cp/parser.cc:48064
0x8eaf19 c_common_parse_file()
	../.././gcc/c-family/c-opts.cc:1240
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
make: *** [tcrmatch] Error 1

Thanks!
Parvathi.

**Comment by parvathisudha** [comment]
Thanks for your reply. Will I be able to run this in MacOS?

**Comment by raphaeltrevizani** [comment]
If it's an intel Mac, very likely. If it's an M-series, see this thread please: https://github.com/IEDB/TCRMatch/issues/49

**Comment by parvathisudha** [comment]
https://github.com/IEDB/TCRMatch/issues/49#issuecomment-1733781905
